name:               godot-ser
version:            0.1.0.0
license:            NONE
author:             Vito Canadi
maintainer:         vito.canadi@gmail.com
extra-source-files: CHANGELOG.md

dependencies:
  - base
  - bytestring
  - containers
  - network
  - linear
  - lens
  - text
  - data-default
  - text
  - utf8-string
  - pretty-simple
  - attoparsec
  - store

library:
  source-dirs: src

tests:
  spec:
    build-depends:
    - base
    - hspec
    - godot-ser
    main: Spec.hs
    source-dirs: spec
version: 0.1.0.0
