name:               godot-ser
version:            0.1.0.0
license:            NONE
author:             Vito Canadi
maintainer:         vito.canadi@gmail.com
extra-source-files: CHANGELOG.md
synopsis:           Binary [de]serialization compatible with Godot game engine's default serialization (var_to_bytes, bytes_to_var)
dependencies:
  - base
  - bytestring
  - containers
  - data-default
  - attoparsec
  - store

library:
  source-dirs: src

tests:
  spec:
    build-depends:
    - base
    - hspec
    - godot-ser
    main: Spec.hs
    source-dirs: spec
version: 0.1.0.0
